import json
from groq import Groq
from fastapi import HTTPException, status
from ..core.config import settings

class AIDetectorService:
    def __init__(self):
        if settings.GROQ_API_KEY:
            self.client = Groq(api_key=settings.GROQ_API_KEY)
            self.model_id = 'llama-3.3-70b-versatile'
        else:
            self.client = None
            self.model_id = None

    async def detect_ai_generated(self, resume_text: str) -> dict:
        fallback_result = {
            "ai_generated_probability": 0.0,
            "confidence_level": "Low",
            "reasoning": "AI detection service currently unavailable. Using default safety values."
        }

        if not self.client:
            return fallback_result

        prompt = f"""
        Analyze the following resume text and determine the probability that it was generated by an AI (like ChatGPT or Gemini).
        
        Provide a deep, structural analysis. Look for patterns like perfectly consistent bullet point lengths, generic professional summaries, and lack of specific personal context.
        
        Return the result STRICTLY as a JSON object with the following structure:
        {{
            "ai_generated_probability": number (0-100),
            "confidence_level": "Low" | "Medium" | "High", // MUST match the probability: 0-20% is Low, 21-40% is Medium, >40% is High
            "reasoning": "A comprehensive, detailed paragraph (at least 150 words) explaining specific linguistic patterns, structural tells, and evidence used to reach this score. Be exhaustive and professional."
        }}

        Resume Text:
        {resume_text}
        """

        try:
            response = self.client.chat.completions.create(
                model=self.model_id,
                messages=[
                    {"role": "system", "content": "You are a professional AI content detector. Analyze text structures and return analysis in STRICT JSON format."},
                    {"role": "user", "content": prompt}
                ],
                response_format={"type": "json_object"},
            )
            
            # Safely parse JSON response
            try:
                result = json.loads(response.choices[0].message.content)
                return result
            except json.JSONDecodeError:
                # Fallback in case the model returns something slightly off
                print(f"AIDetector JSON Error: {response.text}")
                return {
                    "ai_generated_probability": 15.0, # Slight jitter for unparseable but active response
                    "confidence_level": "Low",
                    "reasoning": "AI model returned unparseable content. Fallback applied."
                }

        except Exception as e:
            import traceback
            print(f"AIDetector General Error: {e}")
            traceback.print_exc()
            return fallback_result

ai_detector_service = AIDetectorService()
