import re
import json
from groq import Groq
from fastapi import HTTPException, status
from ..core.config import settings
from ..core.groq_helper import execute_groq_call, parse_json_from_response

class AIDetectorService:
    def __init__(self):
        if settings.GROQ_API_KEY:
            self.client = Groq(api_key=settings.GROQ_API_KEY)
            self.model_id = settings.GROQ_MODEL_ID
        else:
            self.client = None
            self.model_id = None

    async def detect_ai_generated(self, resume_text: str) -> dict:
        fallback_result = {
            "ai_generated_probability": 0.0,
            "confidence_level": "Low",
            "reasoning": "AI detection service currently unavailable. Using default safety values."
        }

        if not self.client or not resume_text or resume_text.startswith("ERROR:"):
            return fallback_result

        prompt = f"""
        Analyze the following resume text and determine the probability that it was generated by an AI (like ChatGPT or Gemini).
        
        Provide a deep, structural analysis. Look for patterns like perfectly consistent bullet point lengths, generic professional summaries, and lack of specific personal context.
        
        Return the result STRICTLY as a JSON object with the following structure:
        {{
            "ai_generated_probability": number (0-100),
            "confidence_level": "Low" | "Medium" | "High", // MUST match the probability: 0-20% is Low, 21-40% is Medium, >40% is High
            "reasoning": "A comprehensive, detailed paragraph (at least 150 words) explaining specific linguistic patterns, structural tells, and evidence used to reach this score. Be exhaustive and professional."
        }}

        Resume Text:
        {resume_text[:4000]}
        """

        try:
            messages = [
                {"role": "system", "content": "You are a professional AI content detector. Analyze text structures and return analysis in STRICT JSON format with NO markdown code blocks or extra text."},
                {"role": "user", "content": prompt}
            ]
            response = await execute_groq_call(self.client, self.model_id, messages)
            
            # Safely parse JSON response using robust helper
            try:
                content = response.choices[0].message.content
                result = parse_json_from_response(content)
                return result
            except Exception as parse_err:
                print(f"AIDetector JSON Error: {parse_err}")
                return {
                    "ai_generated_probability": 15.0,
                    "confidence_level": "Low",
                    "reasoning": "AI model returned unparseable content. Fallback applied."
                }

        except Exception as e:
            import traceback
            print(f"AIDetector General Error: {e}")
            return fallback_result

ai_detector_service = AIDetectorService()

